version: "3.5"

services:
   cut:
      container_name: cut
      image: kfilippov/cut-app:latest
#      build:
#        context: ../
#        dockerfile: docker/dockerfile

      port:
       - 8080:80

#      volume:
#       - /opt/cut-data:/data
      
      restart: always